export declare enum v1PipelineStatus {
    STATUS_UNSPECIFIED = "STATUS_UNSPECIFIED",
    STATUS_RUNNING = "STATUS_RUNNING",
    STATUS_STOPPED = "STATUS_STOPPED",
    STATUS_DEGRADED = "STATUS_DEGRADED"
}
